version: 2
jobs:
  build:
    working_directory: ~/ionic-cache/
    docker:
      - image: node:7
    steps:
      - checkout
      - restore_cache:
         key: node_modules_{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
         key: node_modules_{{ checksum "yarn.lock" }}
         paths:
           - ~/ionic-cache/node_modules/
      - run:
         name: Lint
         command: yarn run lint
      - run:
         name: Test
         command: yarn test
      - run:
         name: Build
         command: yarn run build
