/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/cache.module';
import * as i2 from '@ionic/storage/dist/storage';
import * as i3 from '@ionic/storage/dist/index';
export const CacheModuleNgFactory:i0.NgModuleFactory<i1.CacheModule> = i0.ɵcmf(i1.CacheModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,
          i2.Storage,i2.provideStorage,[i2.StorageConfigToken]),i0.ɵmpd(512,i3.IonicStorageModule,
          i3.IonicStorageModule,([] as any[])),i0.ɵmpd(512,i1.CacheModule,i1.CacheModule,
          ([] as any[])),i0.ɵmpd(256,i2.StorageConfigToken,{name:'__ionicCache',driverOrder:['indexeddb',
          'sqlite','websql']},([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQkhQUy1OZXcvaW9uaWMtY2FjaGUvc3JjL2NhY2hlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9CSFBTLU5ldy9pb25pYy1jYWNoZS9zcmMvY2FjaGUubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
